import Foundation

/// Protocol for AI-powered content generation services
/// Generates various types of content for properties and listings
protocol ContentGenerationProtocol: AIServiceProtocol {
    /// Generate a compelling property description from property data
    /// - Parameter property: The property to generate a description for
    /// - Returns: Generated property description
    func generateDescription(for property: Property) async throws -> String
    
    /// Generate a property title/headline from property data
    /// - Parameter property: The property to generate a title for
    /// - Returns: Generated property title
    func generateTitle(for property: Property) async throws -> String
    
    /// Generate marketing copy for a property listing
    /// - Parameters:
    ///   - property: The property to generate marketing copy for
    ///   - style: The style of marketing copy to generate
    /// - Returns: Generated marketing copy
    func generateMarketingCopy(for property: Property, style: MarketingStyle) async throws -> String
    
    /// Generate neighborhood insights and highlights
    /// - Parameter location: The location to generate insights for
    /// - Returns: Generated neighborhood description and highlights
    func generateNeighborhoodInsights(for location: Coordinate) async throws -> NeighborhoodInsights
    
    /// Generate property comparison summary
    /// - Parameter properties: Array of properties to compare
    /// - Returns: Generated comparison summary
    func generateComparison(for properties: [Property]) async throws -> String
    
    /// Generate investment analysis summary for a property
    /// - Parameter property: The property to analyze
    /// - Returns: Generated investment analysis
    func generateInvestmentAnalysis(for property: Property) async throws -> InvestmentAnalysis
    
    /// Improve existing property description with AI suggestions
    /// - Parameter description: The existing description to improve
    /// - Returns: Improved description with suggestions
    func improveDescription(_ description: String) async throws -> ContentImprovement
}

/// Different styles of marketing copy that can be generated
enum MarketingStyle: String, Codable {
    case professional = "professional"
    case casual = "casual"
    case luxury = "luxury"
    case familyFriendly = "family_friendly"
    case investor = "investor"
    case firstTimeBuyer = "first_time_buyer"
}

/// Neighborhood insights generated by AI
struct NeighborhoodInsights: Codable {
    /// General description of the neighborhood
    let description: String
    
    /// Key highlights and amenities
    let highlights: [String]
    
    /// Nearby schools information
    let schools: [String]
    
    /// Transportation options
    let transportation: [String]
    
    /// Local amenities (restaurants, shopping, etc.)
    let amenities: [String]
    
    /// Safety and community information
    let community: String
}

/// Investment analysis generated by AI
struct InvestmentAnalysis: Codable {
    /// Overall investment summary
    let summary: String
    
    /// Estimated rental yield
    let estimatedRentalYield: String
    
    /// Market appreciation potential
    let appreciationPotential: String
    
    /// Key investment pros
    let pros: [String]
    
    /// Key investment considerations
    let considerations: [String]
    
    /// Comparable properties analysis
    let comparables: String
}

/// Content improvement suggestions from AI
struct ContentImprovement: Codable {
    /// The improved version of the content
    let improvedContent: String
    
    /// Specific suggestions for improvement
    let suggestions: [String]
    
    /// Confidence score of the improvements (0.0 to 1.0)
    let confidence: Double
    
    /// Keywords that were added or emphasized
    let addedKeywords: [String]
}